URL_AUTH_REGISTER = 'https://stellarburgers.nomoreparties.site/api/auth/register'
URL_HOME = 'https://stellarburgers.nomoreparties.site/'
URL_ORDERS_FEED = 'https://stellarburgers.nomoreparties.site/feed'
URL_LOGIN = 'https://stellarburgers.nomoreparties.site/login'
URL_FORGOT_PASSWORD = 'https://stellarburgers.nomoreparties.site/forgot-password'
URL_RESET_PASSWORD = 'https://stellarburgers.nomoreparties.site/reset-password'
URL_ACCOUNT_PROFILE = 'https://stellarburgers.nomoreparties.site/account/profile'
URL_ACCOUNT_ORDERS_HISTORY = 'https://stellarburgers.nomoreparties.site/account/order-history'
